# Generated by Django 3.1.4 on 2020-12-28 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerNumber', models.IntegerField(verbose_name='Customer Number')),
                ('customerName', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('contactLastName', models.CharField(max_length=50, verbose_name='Contact Last Name')),
                ('contactFirstName', models.CharField(max_length=50, verbose_name='Contact First Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('addressLine1', models.CharField(max_length=50, verbose_name='Address Line 1')),
                ('addressLine2', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='State')),
                ('postalCode', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Postal Code')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('salesRepEmployeeNumber', models.IntegerField(blank=True, default=None, null=True, verbose_name='Sales Employee Number')),
                ('creditLimit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeNumber', models.IntegerField(verbose_name='Employee Number')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('firstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('extension', models.CharField(max_length=10, verbose_name='Extension')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('officeCode', models.CharField(max_length=10, verbose_name='Office Code')),
                ('reportsTo', models.IntegerField(blank=True, default=None, null=True, verbose_name='Report to')),
                ('jobTitle', models.CharField(max_length=50, verbose_name='Job Title')),
            ],
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeCode', models.CharField(max_length=10, verbose_name='Office Code')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('addressLine1', models.CharField(max_length=50, verbose_name='Address Line 1')),
                ('addressLine2', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Address Line 2')),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='State')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('postalCode', models.CharField(max_length=15, verbose_name='Postal Code')),
                ('territory', models.CharField(max_length=10, verbose_name='Territory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField(verbose_name='Order Number')),
                ('productCode', models.CharField(max_length=15, verbose_name='Product Code')),
                ('quantityOrdered', models.IntegerField(verbose_name='Quantity Ordered')),
                ('priceEach', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Each')),
                ('orderLineNumber', models.SmallIntegerField(verbose_name='Order Line Number')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField(verbose_name='Order Number')),
                ('orderDate', models.DateField(default=datetime.datetime(2020, 12, 28, 17, 58, 3, 591062, tzinfo=utc), verbose_name='Order Date')),
                ('requiredDate', models.DateField(default=datetime.datetime(2020, 12, 28, 17, 58, 3, 591062, tzinfo=utc), verbose_name='Required Date')),
                ('shippedDate', models.DateField(blank=True, default=None, null=True, verbose_name='Shipped Date')),
                ('status', models.CharField(max_length=15, verbose_name='Status')),
                ('comments', models.TextField(blank=True, default=None, null=True, verbose_name='Comments')),
                ('customerNumber', models.IntegerField(verbose_name='Customer Number')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerNumber', models.IntegerField(verbose_name='Customer Number')),
                ('checkNumber', models.CharField(max_length=50, verbose_name='Check Number')),
                ('paymentDate', models.DateField(default=datetime.datetime(2020, 12, 28, 17, 58, 3, 591062, tzinfo=utc), verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productLine', models.CharField(max_length=50, verbose_name='Product Line')),
                ('textDescription', models.CharField(max_length=4000, verbose_name='Text Description')),
                ('htmlDescription', models.TextField(blank=True, default=None, null=True, verbose_name='HTML Description')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCode', models.CharField(max_length=15, verbose_name='Product Code')),
                ('productName', models.CharField(max_length=70, verbose_name='Product Name')),
                ('productLine', models.CharField(max_length=50, verbose_name='Product Line')),
                ('productScale', models.CharField(max_length=10, verbose_name='Product Scale')),
                ('productVendor', models.CharField(max_length=50, verbose_name='Product Vendor')),
                ('productDescription', models.TextField(verbose_name='Product Description')),
                ('quantityInStock', models.SmallIntegerField(verbose_name='Quantity In Stock')),
                ('buyPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Buy Price')),
                ('MSRP', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MSRP')),
            ],
        ),
    ]
